"""reestructurar appointments para calendario interno

Revision ID: f4319b79a072
Revises: 20260925_0001
Create Date: 2026-10-06 01:30:39.822984
"""
from alembic import op
import sqlalchemy as sa



revision = 'f4319b79a072'
down_revision = '20260925_0001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema='vetki') as batch_op:
        batch_op.add_column(sa.Column('appointment_reason', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('appointment_end_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('appointment_google_event_id')

    with op.batch_alter_table('vaccinations', schema='vetki') as batch_op:
        batch_op.add_column(sa.Column('migration_test', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccinations', schema='vetki') as batch_op:
        batch_op.drop_column('migration_test')

    with op.batch_alter_table('appointments', schema='vetki') as batch_op:
        batch_op.add_column(sa.Column('appointment_google_event_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('appointment_end_date')
        batch_op.drop_column('appointment_reason')

    # ### end Alembic commands ###
